In [1]:
import pandas as pd

df = pd.read_csv("sales_data.csv")

C:\Users\shami\AppData\Local\Temp\ipykernel_27536\4048254719.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [3]:
df.shape

(1000, 14)

In [7]:
df.isnull().sum()

Product_ID              0
Sale_Date               0
Sales_Rep               0
Region                  0
Sales_Amount            0
Quantity_Sold           0
Product_Category        0
Unit_Cost               0
Unit_Price              0
Customer_Type           0
Discount                0
Payment_Method          0
Sales_Channel           0
Region_and_Sales_Rep    0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [12]:
df.dtypes

Product_ID                int64
Sale_Date                object
Sales_Rep                object
Region                   object
Sales_Amount            float64
Quantity_Sold             int64
Product_Category         object
Unit_Cost               float64
Unit_Price              float64
Customer_Type            object
Discount                float64
Payment_Method           object
Sales_Channel            object
Region_and_Sales_Rep     object
dtype: object

In [13]:
df['Sale_Date'] = pd.to_datetime(df['Sale_Date'])
df.dtypes

Product_ID                       int64
Sale_Date               datetime64[ns]
Sales_Rep                       object
Region                          object
Sales_Amount                   float64
Quantity_Sold                    int64
Product_Category                object
Unit_Cost                      float64
Unit_Price                     float64
Customer_Type                   object
Discount                       float64
Payment_Method                  object
Sales_Channel                   object
Region_and_Sales_Rep            object
dtype: object

In [9]:
print("Invalid Sales Amount:", (df['Sales_Amount'] <= 0).sum())
print("Invalid Quantity Sold:", (df['Quantity_Sold'] <= 0).sum())
print("Invalid Unit Cost:", (df['Unit_Cost'] <= 0).sum())
print("Invalid Unit Price:", (df['Unit_Price'] <= 0).sum())
print("Invalid Discount:", ((df['Discount'] < 0) | (df['Discount'] > 1)).sum())

Invalid Sales Amount: 0
Invalid Quantity Sold: 0
Invalid Unit Cost: 0
Invalid Unit Price: 0
Invalid Discount: 0

In [10]:
Q1 = df['Sales_Amount'].quantile(0.25)
Q3 = df['Sales_Amount'].quantile(0.75)

print("Q1:", Q1)
print("Q3:", Q3)

Q1: 2550.2975
Q3: 7507.445000000001

In [14]:
IQR = Q3 - Q1

print("IQR:", IQR)

IQR: 4957.147500000001

In [15]:
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

Lower Limit: -4885.423750000002
Upper Limit: 14943.166250000002

In [16]:
outliers = df[
    (df['Sales_Amount'] < lower_limit) |
    (df['Sales_Amount'] > upper_limit)
]

print("Number of Outliers:", len(outliers))

Number of Outliers: 0

In [17]:
outliers[['Product_ID', 'Sale_Date', 'Region', 'Sales_Amount']].head(10)

Empty DataFrame
Columns: [Product_ID, Sale_Date, Region, Sales_Amount]
Index: []

In [26]:
df[df['Sales_Amount'] < 0]

Empty DataFrame
Columns: [Product_ID, Sale_Date, Sales_Rep, Region, Sales_Amount, Quantity_Sold, Product_Category, Unit_Cost, Unit_Price, Customer_Type, Discount, Payment_Method, Sales_Channel, Region_and_Sales_Rep]
Index: []

In [27]:
df.describe()

,Product_ID,Sale_Date,Sales_Amount,Quantity_Sold,Unit_Cost,Unit_Price,Discount
count,1000.000000,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,1050.128000,2023-07-02 17:42:43.199999744,5019.265230,25.355000,2475.304550,2728.440120,0.15239
min,1001.000000,2023-01-01 00:00:00,100.120000,1.000000,60.280000,167.120000,0.00000
25%,1024.000000,2023-03-30 00:00:00,2550.297500,13.000000,1238.380000,1509.085000,0.08000
50%,1051.000000,2023-06-30 12:00:00,5019.300000,25.000000,2467.235000,2696.400000,0.15000
75%,1075.000000,2023-10-12 00:00:00,7507.445000,38.000000,3702.865000,3957.970000,0.23000
max,1100.000000,2024-01-01 00:00:00,9989.040000,49.000000,4995.300000,5442.150000,0.30000
std,29.573505,NaN,2846.790126,14.159006,1417.872546,1419.399839,0.08720

In [28]:
print("Average Sales:", round(df['Sales_Amount'].mean(), 2))
print("Median Sales:", round(df['Sales_Amount'].median(), 2))
print("Minimum Sales:", round(df['Sales_Amount'].min(), 2))
print("Maximum Sales:", round(df['Sales_Amount'].max(), 2))

Average Sales: 5019.27
Median Sales: 5019.3
Minimum Sales: 100.12
Maximum Sales: 9989.04

In [29]:
correlation = df[
    ['Sales_Amount', 'Quantity_Sold', 'Unit_Cost', 'Unit_Price', 'Discount']
].corr()

correlation

               Sales_Amount  Quantity_Sold  Unit_Cost  Unit_Price  Discount
Sales_Amount       1.000000      -0.041599   0.009770    0.011812  0.023153
Quantity_Sold     -0.041599       1.000000   0.053888    0.057296 -0.007806
Unit_Cost          0.009770       0.053888   1.000000    0.995056 -0.017741
Unit_Price         0.011812       0.057296   0.995056    1.000000 -0.017027
Discount           0.023153      -0.007806  -0.017741   -0.017027  1.000000

In [30]:
df.to_csv("cleaned_sales_data.csv", index=False)

In [32]:
region_sales = df.groupby('Region')['Sales_Amount'].sum().sort_values(ascending=False)

region_sales

Region
North    1369612.51
East     1259792.93
West     1235608.93
South    1154250.86
Name: Sales_Amount, dtype: float64

In [33]:
category_sales = df.groupby('Product_Category')['Sales_Amount'].sum().sort_values(ascending=False)

category_sales

Product_Category
Clothing       1313474.36
Furniture      1260517.69
Electronics    1243499.64
Food           1201773.54
Name: Sales_Amount, dtype: float64

In [34]:
rep_sales = df.groupby('Sales_Rep')['Sales_Amount'].sum().sort_values(ascending=False)

rep_sales

Sales_Rep
David      1141737.36
Bob        1080990.63
Eve         970183.99
Alice       965541.77
Charlie     860811.48
Name: Sales_Amount, dtype: float64

In [35]:
category_quantity = df.groupby('Product_Category')['Quantity_Sold'].sum().sort_values(ascending=False)
category_quantity

Product_Category
Clothing       6922
Furniture      6729
Electronics    6096
Food           5608
Name: Quantity_Sold, dtype: int64

In [36]:
print("Total Revenue:", round(df['Sales_Amount'].sum(), 2))
print("Total Orders:", len(df))
print("Average Order Value:", round(df['Sales_Amount'].mean(), 2))

print("\nBest Region:")
print(region_sales.idxmax(), "-", round(region_sales.max(), 2))

print("\nBest Product Category:")
print(category_sales.idxmax(), "-", round(category_sales.max(), 2))

print("\nBest Sales Representative:")
print(rep_sales.idxmax(), "-", round(rep_sales.max(), 2))

print("\nHighest Quantity Category:")
print(category_quantity.idxmax(), "-", category_quantity.max())

Total Revenue: 5019265.23
Total Orders: 1000
Average Order Value: 5019.27

Best Region:
North - 1369612.51

Best Product Category:
Clothing - 1313474.36

Best Sales Representative:
David - 1141737.36

Highest Quantity Category:
Clothing - 6922